[project]
name = "qoraflow"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    'PyYAML',
    'click',
    "fastparquet>=2026.5.0",
    "h5py",
    "hdf5plugin",
    "ipykernel",
    'jupyter',
    'lmfit',
    'loguru',
    'matplotlib',
    'numpy',
    'pandas',
    "polars>=1.44.1",
    "pyarrow>=25.0.1",
    'pydantic',
    "pyqt5",
    "pyqt6",
    'radon',
    'roi-rectangle',
    'scikit-image',
    'scikit_learn',
    'scipy',
    'tables',
    'tifffile',
    'tqdm',
    'tuna',
    "zarr>=3.1.6",
]

[dependency-groups]
dev = [
    "memory-profiler",
    "ruff",
]
